### ISSUE TITLE
Lookup TreeNode by Key?

### ISSUE THREAD

**Issue by darkfrog26** [embraceitmobile/animated_tree_view#17]
Is there any way to look up a TreeNode by a key? I want to expand a TreeNode within the tree, but I don't have a reference to the node, just its key.

**Comment by darkfrog26** [comment]
I was able to solve this by using the path.

**Comment by claudneysessa** [comment]
> Oi@darkfrog26 você pode compartilhar como

```
var info = widget.controller.treeViewController
                                    ?.elementAt(
                                  path,
                                );
```

The element is a group of keys '/.key1.key2.key3......'
