### ISSUE TITLE
breaking showRootNode in 2.1.0

### ISSUE THREAD

**Issue by abarke** [embraceitmobile/animated_tree_view#18]
Might be worth noting in the CHANGELOG.md that the default for `showRootNode` is now `true` in version 2.1.0.

See https://github.com/embraceitmobile/animated_tree_view/commit/2f80fa5771d840435e7225910afcfd4b38ebdfe8#diff-72fd825ad17ce7800a2078e06f0dff1e12836ee59760465e78d9a5d222cebd15R64

This caused a regression in our app where we did not explicitly set `showRootNode: false`

**Comment by jawwad-hassan89** [comment]
This is definitely an oversight in our part, and apologize for the inconvenience. We will update the changelog to reflect the relevant changes.
