### ISSUE TITLE
question for real world usecase

### ISSUE THREAD

**Issue by ghost** [embraceitmobile/animated_tree_view#2]
Hi @jawwad-hassan89 ,

Hope you are all well !

I am just dropping this message as I would like to create a teampass (https://teampass.net/) clone with flutter.

What would you advice me to use as an architecture for managing permission rights to items categories with view/edit/delete capability. I found flutter_rbac or dart-casbin

Screenshot of teampass:
![pf_tp_5](https://user-images.githubusercontent.com/1963546/143838624-e5b2845f-4954-44e0-8497-1868338a7c51.png)
Thanks for any insights or inputs to help me to boostrap this project.

The bottleneck I see, is that have I hace 30k items to hook in the the tree view. Is It possible to make the tree view searchable ?

Cheers,
Luc

**Comment by jawwad-hassan89** [comment]
I have added this feature to the backlog
