### ISSUE TITLE
How to refresh UI state for node after check-box is clicked on such node?

### ISSUE THREAD

**Issue by UlyssesAlves** [embraceitmobile/animated_tree_view#22]
I need a tree with a checkbox on each of its nodes. My current problem is that the checkbox ui state does not change right after I click the checkbox for that node, but it is then updated correctly when I expand or shrink the tree.

How can I make this work so that when a checkbox os pressed it's UI wii change too on the node?

**Comment by jawwad-hassan89** [comment]
Wrap the node widget in a `ValueListenableBuilder`, and use the node as the `value` to listen. Use `node.data` to assign or get the data.
The node extends the `ValueListenable`, so it can be used as a `ChangeNotifier` or `ValueListenable`.

Apologize for the late reply.

```dart
//sample code
 ValueListenableBuilder(
      valueListenable: node,
      builder: (context, page, child) {
        return SomeWidgetHere();
      },
    );
```
