### ISSUE TITLE
After updating the data, the connected line was disconnected

### ISSUE THREAD

**Issue by Duanyinyin504** [embraceitmobile/animated_tree_view#24]
![0QWFK4FVH}UR}FGO%9NH~)S](https://github.com/embraceitmobile/animated_tree_view/assets/15697958/458b2c57-0c6b-4301-972f-a89e5eb82acd)

**Comment by tomekit** [comment]
Same issue applies to File Explorer Sample
![Uploading Screenshot from 2023-12-22 17-12-41.png…]()

**Comment by tomekit** [comment]
Same issue applies to File Explorer Sample. 
When added data dynamically, e.g. from within the: `onItemTap` method line gets pretty broken:
![Screenshot from 2023-12-22 17-12-41](https://github.com/embraceitmobile/animated_tree_view/assets/7759113/8e1484ff-297e-457f-9ed2-24ab332b1e0d)

**Comment by Uche01** [comment]
Has anyone found a fix for this issue or maybe a different implementation? @tomekit and @Duanyinyin504. I am currently facing this issue.

**Comment by Duanyinyin504** [comment]
> Has anyone found a fix for this issue or maybe a different implementation? @tomekit and @Duanyinyin504. I am currently facing this issue.
