### ISSUE TITLE
Build custom ExpansionIndicator

### ISSUE THREAD

**Issue by AlehSabadashGmail** [embraceitmobile/animated_tree_view#30]
I am slightly confused about building custom ExpansionIndicator, do not know how to do it. Probably you can provide a small example.

**Comment by jawwad-hassan89** [comment]
You will need to extend the `ExpansionIndicator` and `ExpansionIndicatorState` classes in the 
[expansion_indicator.dart](https://github.com/embraceitmobile/animated_tree_view/blob/main/lib/tree_view/widgets/expansion_indicator.dart) file to create custom expansion indicators.

You can use the implementation for `ChevronIndicator` as a reference
