### ISSUE TITLE
Expand on ExpansionIndicator tap instead of on Node tap

### ISSUE THREAD

**Issue by iam1mPerec** [embraceitmobile/animated_tree_view#42]
Is there a possibility to make it so that Expansion happens only on ExpansionIndicator tap but uppon tapping a Node to use onItemTap behavior?

**Comment by iam1mPerec** [comment]
I think I figured it out. I can create a custom node that would pass on a signal to a parent tree when a part of it is clicked. What would be a good way to disable default expand on tap?

**Comment by prakashr** [comment]
I had my node wrapped in a inkwell with an ontap on it. this will consume the clicks on the node but not on the expansion indicator. i did that to select the node (change the color - to indicate its selected). is this what you are looking for?

**Comment by iam1mPerec** [comment]
Yes! Thank you! Exactly What I wanted.
