### ISSUE TITLE
Exception has occurred.

### ISSUE THREAD

**Issue by JrLouis1101** [embraceitmobile/animated_tree_view#7]
Hello, I implemented TreeView.simpleTyped but when I enter the page I get this error:

Exception has occurred.
ActionNotAllowedException (ActionNotAllowedException:
The insertNodes stream is not allowedfor the ListenableNode. The index based operations like 'insert' are not implemented in ListenableNode})

after that, the node tree appears normally. Can someone help me?

**Comment by jawwad-hassan89** [comment]
Hi Louis, are you attempting to listen to the `insertedNodes` stream in your `ListenableNode`? If that is the case, then the exception is merely stating that the `ListenableNode` does not support listening to the stream of `insertedNodes` and that you should remove the listener.
If you really need to listen to the `insertedNodes` then you should use the constructor [TreeView.indexTyped](https://pub.dev/documentation/animated_tree_view/latest/tree_view_tree_view/TreeView/indexTyped.html) instead, as it supports the index based operations like insert.
